# Generated by Django 3.2.15 on 2025-04-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submit_Details',
        ),
    ]
